### ISSUE TITLE
Problem with session when logged on multiple servers

### ISSUE THREAD

**Issue by Esterze** [blitzdose/ServerCtrl#22]
**Describe the bug**
The login sessions get instantly cleared if logged on multiple servers (webinterface).

**To Reproduce**
1. Login on a server
2. Login on another server
3. Refresh the first server

**Expected behavior**
I would like to stay logged in on all of the servers at one moment.

**Minecraft-Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - Plugin-Version 3.3.2

**Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10
 - Plugin-Version: 3.3.2

**Comment by blitzdose** [comment]
Do you run the Webinterfaces just on different ports but the same IP address?
