### ISSUE TITLE
Add Valencian Languaje

### ISSUE THREAD

**Issue by Tsolete** [blitzdose/ServerCtrl#39]
**Language you want to translate to: Valencian (Valencià), form Valencian Community, Spain.

**Comment by blitzdose** [comment]
Hi, thanks but I cannot provide Valencian itself as a language in the App. It's too small and doesn't even have its own language code. I could add the Catalan language if you speak Catalan. Some Google results put Valencian and Catalan together but I don't know if these are the same or just similar.

**Comment by Tsolete** [comment]
The Valencian has his own code on Minecraft (val_es). I have traduced some other plugins to Valencian, (My Pet, Cartographer2, etc...) They are the same variants of the same language, like British English, or American English or Australian English, but I will not translate it to Catalan.

**Comment by blitzdose** [comment]
I understand your point but the plugin itself is only in English. The translation would be only for the apps (Windows, Android, Linux) and the Webinterface. For that, I'm using Flutter (A programming framework) which by default doesn't support Valencian as its own language. Minecraft itself also supports a huge range of languages only a few games support (including pirate English and different versions of german). I am really sorry but there are technical limits to the translation management in Flutter which I cannot overcome.

**Comment by Tsolete** [comment]
No problem. I only wish to help. BTW, your plugin is great, continue doing this great work.
