### ISSUE TITLE
The Chinese output from the minecraft server is garbled when displayed in the "Console" tab of the web page.

### ISSUE THREAD

**Issue by BA7JCM** [blitzdose/ServerCtrl#44]
**Is your feature request related to a problem? Please describe.**
The console page of ServerCtrl cannot display Chinese characters properly, showing them as garbled text. This makes it difficult to understand the output from the Minecraft server.

**Describe the solution you'd like**
I would like the console page to support displaying Chinese characters correctly, so that the output from the Minecraft server can be understood without any issues.

**Describe alternatives you've considered**
One alternative could be to provide an option to specify the character encoding for the console page, allowing users to choose the appropriate encoding for their server's output.

**Additional context**
Currently, the console page only displays garbled text when there are Chinese characters in the output from the Minecraft server.
Note: This content was translated from Chinese using chatgpt. Please forgive me for possible inaccuracies.

**Comment by blitzdose** [comment]
Fixed. Will be available in the next version

**Comment by BA7JCM** [comment]
> Fixed. Will be available in the next version

at version 4.1.0,also command input box can't send commands containing Chinese,such as i try to send "say 测试" command at console page "command" input box,it say "error while sending command",like this:
![image](https://github.com/blitzdose/ServerCtrl/assets/79561519/54c7d7d2-ad36-434b-9bbe-2a8b539607a5)
 
 In the "Network" tab of the browser's developer tools, I saw that the server returned "Server Error",like this:
 
![image](https://github.com/blitzdose/ServerCtrl/assets/79561519/cbf6ff91-7f29-4fd5-bf54-87d64bbb4b39)
