### ISSUE TITLE
title error with the change user permissions page in plugin version 4.1.0

### ISSUE THREAD

**Issue by BA7JCM** [blitzdose/ServerCtrl#47]
**Describe the bug**
I discovered a bug in the web page of this program. In the "Accounts" page, when clicking the "Permissions" button to modify specific user permissions, the title of the popup window for setting permissions is incorrectly set to "Reset Password". Although this does not affect functionality, I would like the author to fix this issue.

**To Reproduce**
1. Go to "Accounts" pages
2. Click on "Permissions" buttons
3. See error

**Expected behavior**
The window displays the correct title, such as "Set Permissions", "Modify Permissions"

**Screenshots**
![image](https://github.com/blitzdose/ServerCtrl/assets/79561519/a61c65e2-adbf-4440-b055-0dbe4c44d98d)

**Additional context**
The screenshots of the  ServerCtrl plugin about page:
![image](https://github.com/blitzdose/ServerCtrl/assets/79561519/6971f792-d673-48ca-9d4f-c34639185ed0)

Because I thought this error might just be a wrongly written string and had nothing to do with the environment, I deleted some of the filling information about the system environment in the template.the plugin version is 4.1.0

**Comment by blitzdose** [comment]
Fixed with in commit ed01c19
