### ISSUE TITLE
Sluggish performance on mobile devices

### ISSUE THREAD

**Issue by aaaaalexis** [blitzdose/ServerCtrl#50]
**Describe the bug**
Extremely poor performance, sluggish scrolling on mobile devices (Android/iOS) on Console tab and text editor.
On iOS device with 3GB of RAM, the page would constantly crash.

**To Reproduce**
1. Go to Console tab or edit any file in Files
2. Lag

**Expected behavior**
Smooth scrolling and usable experience without crashing.

**Versions**
 - OS: Android 13, Android 14, iOS 17.5.1
 - ServerCtrl Version: 4.1.2

**Comment by blitzdose** [comment]
Thank you for the report. Are you using the App on Android or the Web interface? Safari on IOS or another web browser?

**Comment by blitzdose** [comment]
> Sorry for not being clear. All tested on Web interface, Chrome 126 on Android, and Safari on iOS.

Okay thank you. I will have a look. I honestly never tested the app on mobile browsers

**Comment by blitzdose** [comment]
Fixed with 75ed478a1a0bb80f17ad3f3ba89bfdf199cfd2a0 will be available in the next version
