### ISSUE TITLE
PWA showing incorrect icons

### ISSUE THREAD

**Issue by aaaaalexis** [blitzdose/ServerCtrl#51]
**Describe the bug**
ServerCtrl (Web) is showing default Flutter icon instead of custom favicon.

**To Reproduce**
- Add ServerCtrl (Web) as App in any Chromium browser
- Add ServerCtrl (Web) as Favorites in Safari on iOS
- Add ServerCtrl (Web) to Home Screen on iOS

**Expected behavior**
Displaying icon should be the green ServerCtrl icon.

**Screenshots**
![ios](https://github.com/blitzdose/ServerCtrl/assets/65268477/e8804941-ae25-4724-99c7-e0243f06d16c)
![edge](https://github.com/blitzdose/ServerCtrl/assets/65268477/71d5f102-0a2b-422c-a877-7cca49c3d6f5)

**Versions**
 - Microsoft Edge 126 on macOS 14.5
 - Safari on iOS 17.5.1

**Additional context**
Possible fix - Replace icons in https://github.com/blitzdose/ServerCtrl/tree/master/App/web/icons
But I do not have a Flutter env to test so this is an issue instead of a PR.

**Comment by blitzdose** [comment]
Fixed with 674297a5d0d3e7bbf08642211bfefb991a34412d Will be available in the next version
