### ISSUE TITLE
Credentials autofill not working on login page

### ISSUE THREAD

**Issue by aaaaalexis** [blitzdose/ServerCtrl#52]
**Describe the bug**
Password managers unable to autofill credentials on login page of ServerCtrl (Web).

**To Reproduce**
1. Go to any ServerCtrl web instance
2. Autofill using password manager
3. Nothing is filled, password manager unable to file textfield.

**Versions**
- Bitwarden Extension, Microsoft Edge 126 on Windows 11
- Bitwarden Extension, Microsoft Edge 126 on macOS 14.5
- Bitwarden App, Safari on iOS 17.5.1
- Bitwarden App, Chrome 126 on Android 14

**Possibly Related Issues**
Autofill doesn't work with password managers on web https://github.com/flutter/flutter/issues/61301

**Comment by blitzdose** [comment]
I got it to work on desktop when focusing the username field and then doing the autofill. On Android it's not working. I can't do anything about it. There seems to be a problem with flutter itself
