### ISSUE TITLE
Quick suggestion regarding ports

### ISSUE THREAD

**Issue by GrinchBob43** [blitzdose/ServerCtrl#57]
First of all, let me say how much I love this plugin. It is very polished and well built! But I would like to bring up that, because I host multiple servers from one machine, it is only possible to use this plugin on one server at a time, because the port number it binds to is hard-coded. As a suggestion, could you make it so that the port can be changed somehow, either in the config.yml file or somewhere like that? Thanks!

**Comment by blitzdose** [comment]
Thanks for the feedback but that's already possible. The port is in the config.yml. You should be able to just change it.

**Comment by GrinchBob43** [comment]
Hahaha, I see. Sorry to trouble you! Once again, great app! Thank you for you help, I shall use this plugin until I die
